---
- hosts: all

  vars_files:
    - defaults/main.yml
    - vars/main.yml

  vars:
    domain: test.dev

  roles:
    - role: bbatsche.Nginx
      passenger_app: yes

  tasks:
    - import_tasks: tasks/main.yml
