---
- hosts: all

  vars:
    domain: test.dev
  vars_files:
    - defaults/main.yml
    - vars/main.yml
  roles:
    - role: bbatsche.Base
    - role: bbatsche.Nginx
      site_type: ruby
  tasks:
    - include: tasks/main.yml
