---
- hosts: all
  remote_user: vagrant
  become: yes

  vars:
    console_user: vagrant

  roles:
    - bbatsche.Base

  tasks:
  - name: Always Expand Bash Aliases
    copy:
      content: shopt -s expand_aliases;
      dest: /etc/profile.d/alias.sh

  - name: Accept All Environment Variables from SSH
    lineinfile:
      line: AcceptEnv *
      regexp: ^AcceptEnv
      dest: /etc/ssh/sshd_config
      validate: /usr/sbin/sshd -t -f %s
    notify: Restart SSH

  handlers:
  - name: Restart SSH
    service: name=ssh state=restarted
