---
- name: Install Build Dependencies
  apt: name={{ item }} state=present
  with_items:
    - libreadline-dev
    - libssl-dev
    - zlib1g-dev
  become: yes

- name: Create Rbenv Directory
  file:
    path: "{{ rbenv_root }}"
    state: directory
    owner: root
    group: web-admin
    mode: 02775
  become: yes

- name: Allow Web Admins to Write Rbenv Root
  acl:
    name: "{{ rbenv_root }}"
    etype: group
    entity: web-admin
    permissions: rwx
    state: present
  become: yes

- name: Allow Web Admins Write to Future Directories
  acl:
    name: "{{ rbenv_root }}"
    etype: group
    entity: web-admin
    permissions: rwx
    default: yes
    state: present
  become: yes

- name: Set ACL Mask for Future Directories
  acl:
    name: "{{ rbenv_root }}"
    etype: mask
    permissions: rwx
    default: yes
    state: present
  become: yes

- name: Install Rbenv
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: "{{ rbenv_root }}"
    version: "{{ rbenv_version }}"

- name: Install Rbenv Plugins
  git:
    repo: https://github.com/rbenv/{{ item.name }}.git
    dest: "{{ rbenv_root }}/plugins/{{ item.name }}/"
    version: "{{ item.version }}"
  with_items:
    - { name: ruby-build,         version: "{{ ruby_build_version }}" }
    - { name: rbenv-vars,         version: "{{ rbenv_vars_version }}" }
    - { name: rbenv-default-gems, version: "{{ default_gems_version }}" }

- name: Install Binstubs
  git:
    repo: https://github.com/ianheggie/rbenv-binstubs.git
    dest: "{{ rbenv_root }}/plugins/rbenv-binstubs/"
    version: "{{ binstubs_version }}"

- name: Set Default Gems
  copy: src=default-gems dest={{ rbenv_root }}/default-gems

- name: Add Rbenv to Profile
  template: src=rbenv.sh.j2 dest=/etc/profile.d/rbenv.sh mode=755
  become: yes

- name: Install
  shell: . /etc/profile.d/rbenv.sh && rbenv install {{ ruby_version }}
  args:
    creates: "{{ rbenv_root }}/versions/{{ ruby_version }}"

- name: Copy config.ru Stub
  template: src=config.ru.j2 dest={{ http_root }}/{{ domain }}/config.ru
  when: copy_configru
  notify: Restart Passenger App
